# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd337eee0cd5219f1bd8361d7abba533edd6664015c9e8357eb3a4b3e180d173d172d8faf8d26243547f03a81acded74214b0e0146ef5726829c249b0fdb3dd8

test:
  secret_key_base: dff928ef3ecff8ce8efe3e19b2be43852789927d46d4892944175b791d78de9b0565e962cbc80ed175c88fa354f42c4e99506c9cbce31fe59a335f35063cec46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
